@host = http://localhost
@port = 3333
@url = {{host}}:{{port}}

### GET all records from :table

GET {{url}}/kategoria
Content-Type: application/json

### GET one records from :table by :id

GET {{url}}/kategoria/2
Content-Type: application/json

### POST new record to :table

POST {{url}}/kategoria
Content-Type: application/json

{
    "categoryName": "Édességek"
}

### POST new record to :table

POST {{url}}/termekek
Content-Type: application/json

{
    "name": "Boci csoki",
    "catId": 23, 	
    "unit": "db", 	
    "price": 515 	
}

### UPDATE record from :table by :id

PATCH {{url}}/kategoria/23
Content-Type: application/json

{
    "categoryName": "xxxxxxxxxx"
}


### login

POST {{url}}/users/login
Content-Type: application/json

{
    "email": "teszt@gmail.com",
    "password": "123456"
}


### regisztartion

POST  {{url}}/users/registration
Content-Type: application/json

{
    "name": "Sanyi",
    "email": "sanyi@gamil.com",
    "password": "Titkos123456",
    "confirm": "Titkos123456"
}


### 

GET {{url}}/users/id/lte/3
Content-Type: application/json